// <auto-generated />
using AIFantasyPremierLeague.API.Repository.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIFantasyPremierLeague.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120120457_Fixtures2")]
    partial class Fixtures2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AIFantasyPremierLeague.API.Repository.Data.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "first_name");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "element_type");

                    b.Property<int>("PredictedPoints")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "now_cost");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "second_name");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "team");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AIFantasyPremierLeague.API.Repository.Data.PlayerPerformanceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FixtureId")
                        .HasColumnType("int");

                    b.Property<int>("GameWeek")
                        .HasColumnType("int");

                    b.Property<int>("IsHome")
                        .HasColumnType("int");

                    b.Property<int>("OpponentTeam")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayerHistory");
                });

            modelBuilder.Entity("AIFantasyPremierLeague.API.Repository.Data.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "short_name");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("AIFantasyPremierLeague.API.Repository.Data.TeamFixtureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OpponentTeam")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "team_a");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "team_h");

                    b.Property<int>("Week")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "event");

                    b.HasKey("Id");

                    b.ToTable("TeamFixtures");
                });

            modelBuilder.Entity("AIFantasyPremierLeague.API.Repository.Data.TeamHistoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PointsConceded")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TeamHistorys");
                });

            modelBuilder.Entity("AIFantasyPremierLeague.API.Repository.Data.PlayerPerformanceEntity", b =>
                {
                    b.OwnsOne("AIFantasyPremierLeague.API.Repository.Data.PlayerStats", "Stats", b1 =>
                        {
                            b1.Property<string>("PlayerPerformanceEntityId")
                                .HasColumnType("varchar(255)");

                            b1.Property<int>("Assists")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "assists");

                            b1.Property<int>("Bonus")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "bonus");

                            b1.Property<int>("CleanSheets")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "clean_sheets");

                            b1.Property<int>("Goals")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "goals_scored");

                            b1.Property<int>("GoalsConceded")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "goals_conceded");

                            b1.Property<int>("MinsPlayed")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "minutes");

                            b1.Property<int>("Points")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "total_points");

                            b1.Property<int>("RedCards")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "red_cards");

                            b1.Property<int>("Saves")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "saves");

                            b1.Property<int>("YellowCards")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "yellow_cards");

                            b1.HasKey("PlayerPerformanceEntityId");

                            b1.ToTable("PlayerHistory");

                            b1.HasAnnotation("Relational:JsonPropertyName", "stats");

                            b1.WithOwner()
                                .HasForeignKey("PlayerPerformanceEntityId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
